/*
Deployment script for HFS

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "HFS"
:setvar DefaultFilePrefix "HFS"
:setvar DefaultDataPath ""
:setvar DefaultLogPath ""

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
USE [$(DatabaseName)];


GO
PRINT N'Rename refactoring operation with key  is skipped, element [dbo].[Table].[NewLowInd] (SqlSimpleColumn) will not be renamed to NearLowInd';


GO

IF (SELECT OBJECT_ID('tempdb..#tmpErrors')) IS NOT NULL DROP TABLE #tmpErrors
GO
CREATE TABLE #tmpErrors (Error int)
GO
SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
GO
BEGIN TRANSACTION
GO
PRINT N'Creating [dbo].[Quote]...';


GO
CREATE TABLE [dbo].[Quote] (
    [Id]          INT           NOT NULL,
    [Symbol]      NVARCHAR (10) NOT NULL,
    [Q_Last]      NVARCHAR (50) NOT NULL,
    [Q_Change]    NVARCHAR (50) NOT NULL,
    [Q_52Wk_High] NVARCHAR (50) NOT NULL,
    [Q_52Wk_Low]  NVARCHAR (50) NOT NULL,
    [PEG]         NVARCHAR (50) NOT NULL,
    [PE]          NVARCHAR (50) NOT NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating [dbo].[System]...';


GO
CREATE TABLE [dbo].[System] (
    [Id]                    INT          NOT NULL,
    [MyToday]               DATETIME     NULL,
    [PlusMinusDays]         DECIMAL (18) NULL,
    [GoldCoinPrem]          DECIMAL (18) NULL,
    [NearLowInd]            DECIMAL (18) NULL,
    [NewHighInd]            DECIMAL (18) NULL,
    [ProtWarningShort]      DECIMAL (18) NULL,
    [ProtWarningLong]       DECIMAL (18) NULL,
    [ProtWarningStart]      DECIMAL (18) NULL,
    [AlertsShowAdvanceDays] BIT          NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO

IF EXISTS (SELECT * FROM #tmpErrors) ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT>0 BEGIN
PRINT N'The transacted portion of the database update succeeded.'
COMMIT TRANSACTION
END
ELSE PRINT N'The transacted portion of the database update failed.'
GO
DROP TABLE #tmpErrors
GO
PRINT N'Update complete.';


GO
